export { Hero } from './Hero'
export { Services } from './Services'
export { About } from './About'
export { Testimonials } from './Testimonials'
export { CTA } from './CTA'
export { Contact } from './Contact'
export { Map } from './Map'
export { Footer } from './Footer'
